#spring.application.name=patient-management-service

spring:
  application:
    name: patient-management-service
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/patient_db}
    username: ${SPRING_DATASOURCE_USERNAME:patient_user}
    password: ${SPRING_DATASOURCE_PASSWORD:patient_password}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}
