#spring.application.name=appointment-service

server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/appointment_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

# External services
services:
  patient:
    url: http://patient-management-service:8082